GET http://localhost:4000/v1/promt 
###

POST http://localhost:4000/v1/promt 
Content-Type: application/json

{
    "title":"Boys Model Style",
    "descrption":"testing api",
    "imageUrl":"/image.png",
    "promtType":"Boys"
}

###

GET http://localhost:4000/v1/promt/68d61805d91b70d4016e02f8

###

PUT  http://localhost:4000/v1/promt/68d61805d91b70d4016e02f8
Content-Type: application/json

{
    "title":"Stejo",
    "descrption":"testing api",
    "imageUrl":"/image.png",
    "promtType":"Boys",
}

###

DELETE   http://localhost:4000/v1/promt/68d61b4edcbb927a469706fc
